# 02 Numpy

**Phase:** Phase1_Python_Pandas  
**Status:** 🟢 Done    
**Date Started:** 21-05-26

---


In [8]:
# Question 1 -----------

import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.arange(0, 10, 2)
c = np.zeros((3, 3))
# What is the difference between a and a regular Python list
# What does b contain?
# What does c look like and what is its shape?

here in numpy a actually represent the arrays but in python list they are different objects the main difference i can recall is the storage, array are stored in contigious memory location while list are dynamically stored second i can say is numpy is written in c so working with array are more memroy efficient and faster than lists 

b will return array from 0 to 10(excluded) with step of 2 so i think it will be 0,2,4,6,8 

and in c we have array of dimension 3*3 so total element(size) will be 9 and shape (3*3) all filled with 0.

#### major miss 

In [10]:
# List — can hold mixed types
my_list = [1, "hello", True, 3.14]

# NumPy array — enforces ONE dtype for all elements
my_array = np.array([1, 2, 3, "hello"])
print(my_array)  # → ['1' '2' '3' 'hello'] — converts everything to string!

# bool → int → float → complex → string

['1' '2' '3' 'hello']


In [28]:
# Question - 2 ------------

arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

In [22]:
# How do you get the value 60?
print(arr[1,2])
print(arr.item(5))

# How do you get the entire second row?
print(arr[1:2])
print(arr[1])

# How do you get this sub-array: [[20, 30], [50, 60]]?
print(arr[0:2,1:3])

60
60
[[40 50 60]]
[40 50 60]
[[20 30]
 [50 60]]


In [31]:
# Questoion - 3 ---------
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

ok so one think i remember is both arrays must have same size 

in case of different shape one must have space of (1,x) or (x,1) and x must be row or col of second array , such that both will result to same shape and size 

here what will happen is 
the operation will be performed over the values of array base on their similar index 

so 
for 1>
[11,22,33,44]

for 2>
[20,40,60,80]

for 3>
[100,400,900,1600]

now if these were python list 


'+'  is considered as append , result [10,20,30,40,1,2,3,4]

and * will be considered as repeat , result [10,20,30,40,10,20,30,40]

and the power will raise an error as nothing like this is supported in terms of list

In [35]:
# Question 4 -------------

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# arr.shape → ?
# arr.size → ?
# arr.ndim → ?
# arr.dtype → ?

arr.shape → 3,4

arr.size → 12

arr.ndim → 2

arr.dtype → int64

In [36]:
scores = np.array([[85, 42, 91],
                   [78, 95, 33],
                   [60, 71, 88]])

In [49]:
# Four parts:

# Get the mean score of each student (row-wise)
for i in range(0,3):
    print(scores[i].mean())

print(scores.mean(axis=1))
print(scores.mean(axis=0))

# Get the highest score in the entire array
print(scores.max())

# Get all scores above 70 using boolean indexing
scores[scores>70]

# What is the shape, size and ndim of this array? 
# shape -> 3,3
# size -> 9
# ndim -> 2


72.66666666666667
68.66666666666667
73.0
[72.66666667 68.66666667 73.        ]
[74.33333333 69.33333333 70.66666667]
95


array([85, 91, 78, 95, 71, 88])

### axis=1 → traverse row by row → one result per row
### axis=0 → traverse col by col → one result per col

#### Takeaways 

- ndim — number of dimensions
- axis=0 vs axis=1 — collapse rows vs columns
- dtype hierarchy — bool → int → float → complex → string
- Always prefer vectorized operations over loops in NumPy